project_name: sbomqs

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true 

builds:
  - id: binaries 
    binary: sbomqs-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true 
    main: .
    flags:
      - -trimpath 
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - darwin
      - windows 
    goarch:
      - amd64
      - arm64
    ldflags:
      - "{{ .Env.LDFLAGS }}"
    env: 
      - CGO_ENABLED=0

archives:
- format: binary
  name_template: "{{ .Binary }}"
  allow_different_binary_count: true 

snapshot: 
  name_template: SNAPSHOT-{{ .ShortCommit }}

release:
  prerelease: allow 
  draft: true 
  

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.spdx.sbom"
    cmd: syft
    args: ["$artifact", "--file", "$sbom", "--output", "spdx-json"]
  
archives:
  - name_template: "sbomqs_{{ .Version }}_{{ .Os }}_{{ .Arch }}"  
    replacements:
      amd64: x86_64

project_name: sbomqs

# Check https://goreleaser.com/customization/homebrew/
brews:
  - homepage: 'https://github.com/kchetans/brew-repo'
    description: 'Binary distribution using homebrew.'
    folder: Formula
    tap:
      owner: kchetans
      name: brew-repo

